name: Truth_Table_Test
on:            # Feature Branches
  pull_request:
    branches:
      - 'main'       
  
jobs:
  Test_Truth_Table:
    permissions: write-all
    runs-on: hermeling-runner-set
    container:
      image: kicad/kicad:8.0.2
    steps:
      - name: run tests
        run: run.sh > test_results.txt
      - name: upload test results 
        uses: actions/upload-artifact@v2
        with:
            name: test_results
            path: test_results.txt
           